from uuid import UUID
from datetime import datetime, timezone
from typing import Optional, Sequence

from sqlalchemy import select, and_, exists
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.insight import Insight, InsightType, InsightSeverity


_VALID_ACTIONS = {"accept", "dismiss", "snooze"}


class InsightService:
    """
    Service for managing user insights.

    Insights are observations and suggestions generated by the adaptive
    engine from a user's check-ins, labs, wearable data, and protocol
    history. Each insight carries a confidence score and an explanation
    of why it was generated.
    """

    def __init__(self, db: AsyncSession):
        self.db = db

    async def get_by_id(self, insight_id: UUID, user_id: UUID) -> Optional[Insight]:
        """Get an insight by ID, ensuring it belongs to the specified user."""
        result = await self.db.execute(
            select(Insight).where(
                and_(
                    Insight.id == insight_id,
                    Insight.user_id == user_id,
                )
            )
        )
        return result.scalar_one_or_none()

    async def list_for_user(
        self,
        user_id: UUID,
        unread_only: bool = False,
        type: Optional[InsightType] = None,
        severity: Optional[InsightSeverity] = None,
        include_dismissed: bool = False,
        limit: int = 100,
        offset: int = 0,
    ) -> Sequence[Insight]:
        """
        List insights for a user, ordered by creation time (newest first).
        """
        query = select(Insight).where(Insight.user_id == user_id)

        if unread_only:
            query = query.where(Insight.read_at.is_(None))
        if not include_dismissed:
            query = query.where(Insight.dismissed_at.is_(None))
        if type is not None:
            query = query.where(Insight.type == type)
        if severity is not None:
            query = query.where(Insight.severity == severity)

        query = query.order_by(Insight.created_at.desc()).offset(offset).limit(limit)

        result = await self.db.execute(query)
        return result.scalars().all()

    async def create(
        self,
        user_id: UUID,
        type: InsightType,
        severity: InsightSeverity,
        title: str,
        description: str,
        explanation: str,
        confidence: float,
        source_data_refs: Optional[str] = None,
    ) -> Insight:
        insight = Insight(
            user_id=user_id,
            type=type,
            severity=severity,
            title=title,
            description=description,
            explanation=explanation,
            confidence=confidence,
            source_data_refs=source_data_refs,
        )
        self.db.add(insight)
        await self.db.commit()
        await self.db.refresh(insight)
        return insight

    async def exists_matching(
        self,
        user_id: UUID,
        type: InsightType,
        source_data_refs: Optional[str],
    ) -> bool:
        """Check if an insight with the same type and source_data_refs exists for this user."""
        query = select(
            exists().where(
                and_(
                    Insight.user_id == user_id,
                    Insight.type == type,
                    Insight.source_data_refs == source_data_refs,
                )
            )
        )
        result = await self.db.execute(query)
        return result.scalar()

    async def mark_read(self, insight: Insight) -> Insight:
        """
        Mark an insight as read.

        Stamps read_at if not already set (idempotent on read_at), and
        always clears any prior action so the insight returns to a
        "seen but not yet actioned" state.
        """
        if insight.read_at is None:
            insight.read_at = datetime.now(timezone.utc)

        insight.action_taken = None
        insight.action_notes = None
        insight.dismissed_at = None

        await self.db.commit()
        await self.db.refresh(insight)
        return insight

    async def record_action(
        self,
        insight: Insight,
        action: str,
        notes: Optional[str] = None,
    ) -> Insight:
        """
        Record the user's action on an insight (accept / dismiss / snooze).

        Dismiss also stamps dismissed_at so dismissed insights can be
        filtered out of active views without losing the record.
        """
        if action not in _VALID_ACTIONS:
            raise ValueError(f"Invalid action: {action}. Must be one of {_VALID_ACTIONS}.")

        insight.action_taken = action
        insight.action_notes = notes
        if action == "dismiss":
            insight.dismissed_at = datetime.now(timezone.utc)

        await self.db.commit()
        await self.db.refresh(insight)
        return insight
