"""initial schema

Revision ID: 19381cefe6c7
Revises: 
Create Date: 2026-06-02 16:17:50.082660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.base import GUID


# revision identifiers, used by Alembic.
revision: str = '19381cefe6c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('waitlist_entries',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_entries_email'), 'waitlist_entries', ['email'], unique=True)
    op.create_table('checkins',
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('appetite_level', sa.Integer(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('nausea', sa.Integer(), nullable=True),
    sa.Column('injection_site_reaction', sa.Integer(), nullable=True),
    sa.Column('fatigue', sa.Integer(), nullable=True),
    sa.Column('headache', sa.Integer(), nullable=True),
    sa.Column('gi_issues', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_date'), 'checkins', ['date'], unique=False)
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.Enum('IOS', 'ANDROID', name='deviceplatform'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_tokens_token'), 'device_tokens', ['token'], unique=False)
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('insights',
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('type', sa.Enum('ANOMALY', 'TREND', 'SUGGESTION', 'MILESTONE', name='insighttype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ALERT', name='insightseverity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('action_notes', sa.Text(), nullable=True),
    sa.Column('source_data_refs', sa.Text(), nullable=True),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_user_id'), 'insights', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('panel_type', sa.String(length=50), nullable=False),
    sa.Column('lab_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_date'), 'lab_results', ['date'], unique=False)
    op.create_index(op.f('ix_lab_results_user_id'), 'lab_results', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('insights_enabled', sa.Boolean(), nullable=False),
    sa.Column('alert_severity_only', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('protocols',
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocols_start_date'), 'protocols', ['start_date'], unique=False)
    op.create_index(op.f('ix_protocols_user_id'), 'protocols', ['user_id'], unique=False)
    op.create_table('wearable_connections',
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('provider', sa.Enum('APPLE_HEALTH', 'OURA', 'WHOOP', name='wearableprovider'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wearable_connections_user_id'), 'wearable_connections', ['user_id'], unique=False)
    op.create_table('wearable_data',
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('provider', sa.Enum('APPLE_HEALTH', 'OURA', 'WHOOP', name='wearableprovider'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality_score', sa.Float(), nullable=True),
    sa.Column('hrv_ms', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Float(), nullable=True),
    sa.Column('steps', sa.Float(), nullable=True),
    sa.Column('active_calories', sa.Float(), nullable=True),
    sa.Column('recovery_score', sa.Float(), nullable=True),
    sa.Column('strain_score', sa.Float(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wearable_data_date'), 'wearable_data', ['date'], unique=False)
    op.create_index(op.f('ix_wearable_data_user_id'), 'wearable_data', ['user_id'], unique=False)
    op.create_table('compounds',
    sa.Column('protocol_id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dose_mg', sa.Float(), nullable=False),
    sa.Column('dose_unit', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('administration_route', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compounds_protocol_id'), 'compounds', ['protocol_id'], unique=False)
    op.create_table('lab_markers',
    sa.Column('lab_result_id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('reference_low', sa.Float(), nullable=True),
    sa.Column('reference_high', sa.Float(), nullable=True),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lab_result_id'], ['lab_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_markers_lab_result_id'), 'lab_markers', ['lab_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_markers_lab_result_id'), table_name='lab_markers')
    op.drop_table('lab_markers')
    op.drop_index(op.f('ix_compounds_protocol_id'), table_name='compounds')
    op.drop_table('compounds')
    op.drop_index(op.f('ix_wearable_data_user_id'), table_name='wearable_data')
    op.drop_index(op.f('ix_wearable_data_date'), table_name='wearable_data')
    op.drop_table('wearable_data')
    op.drop_index(op.f('ix_wearable_connections_user_id'), table_name='wearable_connections')
    op.drop_table('wearable_connections')
    op.drop_index(op.f('ix_protocols_user_id'), table_name='protocols')
    op.drop_index(op.f('ix_protocols_start_date'), table_name='protocols')
    op.drop_table('protocols')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_lab_results_user_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_date'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_insights_user_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_token'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_date'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_waitlist_entries_email'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
